# Setup

In [ ]:
#You might need to install these packages before running. Comment out after
!pip install torch
!pip install transformers datasets
!pip install scikit-learn
!pip install wandb

Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.1.0+cu118)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch) (4.5.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.6.0)
Requirement already satisfied: triton==2.1.0 in /usr/local/lib/python3.10/dist-packages (from torch) (2.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch) (1.3.0)
Collecting transformers
  Downloading transformers-4.35.2-py3-none-any.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 70.4 MB/s eta 0:00:00
Collecting datasets
  Downloading datasets-2.15.0-py3-none-any.whl (521 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 521.2/521.2 kB 55.1 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.13.1)
Collecting huggingface-hub<1.0,>=0.16.4 (from transformers)
  Downloading huggingface_hub-0.19.4-py3-none-any.whl (311 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.7/311.7 kB 45.3 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.23.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2023.6.3)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.31.0)
Collecting tokenizers<0.19,>=0.14 (from transformers)
  Downloading tokenizers-0.15.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 90.2 MB/s eta 0:00:00
Collecting safetensors>=0.3.1 (from transformers)
  Downloading safetensors-0.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 76.7 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.1)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (9.0.0)
Collecting pyarrow-hotfix (from datasets)
  Downloading pyarrow_hotfix-0.5-py3-none-any.whl (7.8 kB)
Collecting dill<0.3.8,>=0.3.0 (from datasets)
  Downloading dill-0.3.7-py3-none-any.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 17.4 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (1.5.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets) (3.4.1)
Collecting multiprocess (from datasets)
  Downloading multiprocess-0.70.15-py310-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 21.2 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]<=2023.10.0,>=2023.1.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (2023.6.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.8.6)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (3.3.2)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.16.4->transformers) (4.5.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2023.7.22)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->datasets) (1.16.0)
Installing collected packages: safetensors, pyarrow-hotfix, dill, multiprocess, huggingface-hub, tokenizers, transformers, datasets
Successfully installed datasets-2.15.0 dill-0.3.7 huggingface-hub-0.19.4 multiprocess-0.70.15 pyarrow-hotfix-0.5 safetensors-0.4.0 tokenizers-0.15.0 transformers-4.35.2
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.23.5)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.3)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.2.0)
Collecting wandb
  Downloading wandb-0.16.0-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 13.2 MB/s eta 0:00:00
Requirement already satisfied: Click!=8.0.0,>=7.1 in /usr/local/lib/python3.10/dist-packages (from wandb) (8.1.7)
Collecting GitPython!=3.1.29,>=1.0.0 (from wandb)
  Downloading GitPython-3.1.40-py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.6/190.6 kB 21.9 MB/s eta 0:00:00
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (2.31.0)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (5.9.5)
Collecting sentry-sdk>=1.0.0 (from wandb)
  Downloading sentry_sdk-1.35.0-py2.py3-none-any.whl (248 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.6/248.6 kB 22.5 MB/s eta 0:00:00
Collecting docker-pycreds>=0.4.0 (from wandb)
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from wandb) (6.0.1)
Collecting setproctitle (from wandb)
  Downloading setproctitle-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from wandb) (67.7.2)
Requirement already satisfied: appdirs>=1.4.3 in /usr/local/lib/python3.10/dist-packages (from wandb) (1.4.4)
Requirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in /usr/local/lib/python3.10/dist-packages (from wandb) (3.20.3)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Collecting gitdb<5,>=4.0.1 (from GitPython!=3.1.29,>=1.0.0->wandb)
  Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 7.9 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.0.0->wandb) (2023.7.22)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython!=3.1.29,>=1.0.0->wandb)
  Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
Installing collected packages: smmap, setproctitle, sentry-sdk, docker-pycreds, gitdb, GitPython, wandb
Successfully installed GitPython-3.1.40 docker-pycreds-0.4.0 gitdb-4.0.11 sentry-sdk-1.35.0 setproctitle-1.3.3 smmap-5.0.1 wandb-0.16.0

In [ ]:
!wandb login

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

In [ ]:
# Run this cell to mount your Google Drive.
# ONLY ON GOOGLE COLAB!
from google.colab import drive
drive.mount('/content/drive')
%cd "/content/drive/My Drive/nlpproject/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/nlpproject

In [ ]:
import wandb
import csv
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForMaskedLM,AutoModelForSequenceClassification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import classification_report, accuracy_score
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
def multi_label_formatting(data):
    """This function does not really play a huge role for us right now, but what it basically does is that if a paragraph
    has two stances, i.e. 'conservative' and 'right', it will keep both for the classification problem.   """
    labels = []
    for i in range(len(data['stance'])):
        multi_tags = []
        if type(data['stance'][i]) is not float:
            multi_tags.append(data['stance'][i].lower())

        labels.append(multi_tags)

    return labels

#Preprocessing the CSV file that contains the BASIL database.
# df = pd.read_csv('processed_data.csv')
df = pd.read_csv('processed_data_combined.csv')

paragraphs = df["body"] # Gets paragraphs from CSV

#This line was intended to convert stances to integers. Is not needed anymore since now we use MultiLabel Binarizer for
# multilabel classification
# df['stance'] = df['stance'].replace([ 'left', 'center', 'liberal', 'conservative', 'right'],[0,1,2,3,4])


stances = df['stance'] # Gets all the stances/labels
# Stances: {'left', 'center', 'liberal', 'conservative', 'right'}
df['body'] =df['body'].astype(str)

In [ ]:
df.head()

,title,body,stance
0,Elizabeth Cheney blasted by older sister over ...,"Call it Cheney versus Cheney.\nMary Cheney, on...",center
1,Mary Cheney: Sister Is 'Dead Wrong' On Gay Mar...,"Mary Cheney, the younger sister of Wyoming U.S...",center
2,IRS official who refused to testify facing mor...,The IRS official who refused to testify at a H...,center
3,White House Plays Down Data Program,WASHINGTON — The Obama administration tried Sa...,center
4,N.R.A. Details Plan for Armed School Guards,Report Sees Guns as Path to Safety in Schools\...,center

In [ ]:
print('dataset size:', df.shape[0])

dataset size: 37854

In [ ]:
# subset = df.sample(n=dataset_size, random_state=0).reset_index(drop=True)
class_size = 200
subset = df.groupby('stance', group_keys=False).apply(lambda x: x.sample(min(len(x), class_size))).reset_index(drop=True)
print(subset.shape)

(600, 3)

In [ ]:
subset.head()

,title,body,stance
0,Facebook CEO Mark Zuckerberg defends decision ...,Facebook CEO and co-founder Mark Zuckerberg on...,center
1,Supreme Court grants NY prosecutors access to ...,The Supreme Court in a split decision on Thurs...,center
2,Why I Am Disappointed With The 2016 Presidenti...,"Nobody ’ s perfect , or so Hannah Montana says...",center
3,Citing 'security concerns' due to government s...,WASHINGTON – House Speaker Nancy Pelosi asked ...,center
4,China Announces Tariff Retaliation to Take Eff...,LISTEN TO ARTICLE 1:50 SHARE THIS ARTICLE Shar...,center

In [ ]:
subset.groupby('stance', group_keys=False).count()

        title  body
stance
center    200   200
left      200   200
right     200   200

In [ ]:
def init_data_model(batch_size, class_size, test_size):

    # Use if you would want to print a sample paragraph and label
    # print(df['body'][100])
    # print(df['stance'][100])

    # subset = df.sample(n=dataset_size, random_state=0).reset_index(drop=True)

    # stratefied sampling of the dataset with even number of each class
    subset = df.groupby('stance', group_keys=False).apply(lambda x: x.sample(min(len(x), class_size))).reset_index(drop=True)

    print('Dataset size:', subset.shape[0])
    print(subset.groupby('stance', group_keys=False).count())


    #This package will convert tags to an array of size 5 (five because we have 5 stances:
    # 'left', 'center', 'liberal', 'conservative', 'right') where, for example, if a paragraph is classified as 'center'
    # it converts its label into one hot encoding [0,0,1,0,0]
    mlb = MultiLabelBinarizer()
    labels = multi_label_formatting(subset) # In case of multitags. Look at function description for more info
    print(f"Labels : {labels}")
    #One Hot Enconding of Multi labels
    labels = mlb.fit_transform(labels)

    #Splitting data into test set and training set.
    x_train_og, x_test_og, y_train, y_test = train_test_split(subset['body'].astype(str), labels,test_size=test_size, random_state = 0)

    #These following two models are way bigger and perform worse (tested.)
    # model_name = "roberta-large"
    # model_name = "roberta-base"

    model_name = "launch/POLITICS" # POLITICS model from HuggingFace!

    tokenizer = AutoTokenizer.from_pretrained(model_name)

    # You can check that maximum amount of tokes is 512 which means that we will not be able
    # to process the entire paragraphs.
    # print(tokenizer.model_max_length)

    # model = AutoModelForMaskedLM.from_pretrained("launch/POLITICS")
    n_labels = 3 # num_labels = 5 enables hugging face to add a classification head to the model
    model = AutoModelForSequenceClassification.from_pretrained (model_name,num_labels=n_labels)

    train_encodings = tokenizer(x_train_og.to_list(), truncation=True, padding=True, return_tensors="pt")
    train_labels = torch.tensor(y_train, dtype=torch.float32)
    train_dataset = TensorDataset(train_encodings.input_ids, train_encodings.attention_mask, train_labels)
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    # Dataloader for test data
    test_encodings = tokenizer(x_test_og.to_list(), truncation=True, padding=True, return_tensors="pt")
    test_labels = torch.tensor(y_test, dtype=torch.float32)
    test_dataset = TensorDataset(test_encodings.input_ids, test_encodings.attention_mask, test_labels)
    test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)  # No need to shuffle test data

    return train_loader, test_loader, model, tokenizer, mlb.classes_


def evaluate(test_loader, model, tokenizer, classes=None, report=False):
    # Predict on the test data
    all_preds = []
    all_labels = []
    with torch.no_grad():
        for batch in test_loader:
            input_ids, attention_mask, labels = batch
            input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)

            outputs = model(input_ids, attention_mask=attention_mask)
            logits = outputs.logits

            # Softmax makes more sense for single classifications
            predictions = outputs.logits.softmax(dim=-1).tolist()
            all_preds.extend(predictions)

            # In case you'd want to use Sigmoid
            # predictions = torch.sigmoid(logits)  # Apply sigmoid activation for multilabel classification
            # all_preds.extend(predictions.cpu().detach().numpy())

            all_labels.extend(labels.cpu().detach().numpy())

    # Convert the predictions and labels to binary values based on a threshold (e.g., 0.5)
    threshold = 0.5

    all_preds = (torch.tensor(all_preds) > threshold).int().numpy()
    all_labels = np.array(all_labels)

    # Compute the classification report
    accuracy = accuracy_score(all_labels, all_preds)

    # Reporting Results
    if report:
      #Bigger report summary. Sample avg is the same as Accuracy.
      report = classification_report(all_labels, all_preds, target_names=classes)
      print(report)

    # return more things want more information
    return accuracy


def train(train_loader, test_loader, model, tokenizer, lr, batch_size, threshold):
    #Optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)

    # # Fine-tuning loop
    model.to(device)

    num_epochs = 20

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0

        for batch in train_loader:
            input_ids, attention_mask, labels = batch
            input_ids, attention_mask, labels = input_ids.to(device), attention_mask.to(device), labels.to(device)

            optimizer.zero_grad()

            # Forward pass
            outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss

            # # Backward pass and optimization
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        train_acc = evaluate(train_loader, model, tokenizer)
        val_acc = evaluate(test_loader, model, tokenizer)

        print(f"train_acc: {train_acc}")
        print(f"val_acc: {val_acc}")

        wandb.log({
            'loss': total_loss,
            'train_acc': train_acc,
            'val_acc': val_acc,
          })

        print(f"Epoch {epoch + 1}/{num_epochs}, Loss: {total_loss}")
        # test_model() Use if you would want to take a look at how the model is currently doing on the test data. BAD PRACTICE!
        if total_loss < threshold:
          break

    return model, tokenizer

# One-off training
This section is for if you just want to train a single model with a given configuration. Record your configuration in the following wandb config, and simply run the training block. The loss will be reported to wandb.

In [ ]:
lr = 0.00003132066331971823
batch_size = 8
test_size = 0.1
threshold = 1.5
class_size = 300

wandb.init(
    project='politics_more_data',
    config= {
        'learning_rate': lr,
        'batch_size': batch_size,
        'test_size': test_size,
        'threshold': threshold,
        'class_size': class_size,
    }
)

wandb: Currently logged in as: ellieyhc (probgram). Use `wandb login --relogin` to force relogin

In [ ]:
# Load model directly
train_loader, test_loader, model, tokenizer, classes = init_data_model(batch_size, class_size, test_size)

Dataset size: 900
        title  body
stance
center    300   300
left      300   300
right     300   300
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

(…)ITICS/resolve/main/tokenizer_config.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

(…)/launch/POLITICS/resolve/main/vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

(…)/launch/POLITICS/resolve/main/merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

(…)nch/POLITICS/resolve/main/tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

(…)ICS/resolve/main/special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

(…)launch/POLITICS/resolve/main/config.json:   0%|          | 0.00/672 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
model, tokenizer = train(train_loader, test_loader, model, tokenizer, lr, batch_size, threshold)

train_acc: 0.6160493827160494
val_acc: 0.4777777777777778
Epoch 1/20, Loss: 62.80589681863785
train_acc: 0.9197530864197531
val_acc: 0.7444444444444445
Epoch 2/20, Loss: 41.02653394639492
train_acc: 0.9111111111111111
val_acc: 0.6666666666666666
Epoch 3/20, Loss: 18.833246557042003
train_acc: 0.9753086419753086
val_acc: 0.7333333333333333
Epoch 4/20, Loss: 11.078716099262238
train_acc: 0.9901234567901235
val_acc: 0.7222222222222222
Epoch 5/20, Loss: 5.5403104135766625
train_acc: 0.8814814814814815
val_acc: 0.6444444444444445
Epoch 6/20, Loss: 6.424322786740959
train_acc: 0.9925925925925926
val_acc: 0.6777777777777778
Epoch 7/20, Loss: 4.627294691745192
train_acc: 0.945679012345679
val_acc: 0.7333333333333333
Epoch 8/20, Loss: 1.4088158505037427

In [ ]:
# final evaluation
acc = evaluate(test_loader, model, tokenizer, classes, report=True)

              precision    recall  f1-score   support

      center       0.92      0.44      0.59        25
        left       0.86      0.74      0.79        34
       right       0.59      0.94      0.72        31

   micro avg       0.72      0.72      0.72        90
   macro avg       0.79      0.70      0.70        90
weighted avg       0.78      0.72      0.71        90
 samples avg       0.72      0.72      0.72        90

In [ ]:
# save the model
save_name = 'politics_best'

model.save_pretrained(save_name)

In [ ]:
wandb.finish()

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

# Hyperparameter Fine-tuning
This section is for doing sweeps over different hyperparameters to fine-tune for the best accuracy.

In [ ]:
sweep_config = {
    'method': 'random',
    'name': 'sweep',
    'metric': {'goal': 'maximize', 'name': 'val_acc'},
    'parameters': {
        'batch_size': {'values': [8, 16]},
        'lr': {'max': 1e-4, 'min': 1e-6},
        # 'test_size': {'values': [0.2, 0.25, 0.3]},
        'threshold': {'values': [0.5, 1, 1.5, 2, 2.5, 3]},
        'class_size': {'values': [100, 150, 200, 250, 300]},
    }
}

sweep_id = wandb.sweep(sweep=sweep_config, project='politics-sweep')

Create sweep with ID: 4zhe9egr
Sweep URL: https://wandb.ai/probgram/politics-sweep/sweeps/4zhe9egr

In [ ]:
def main():
  run = wandb.init()

  lr = wandb.config.lr
  batch_size = wandb.config.batch_size
  # test_size = wandb.config.test_size
  test_size = 0.1
  threshold = wandb.config.threshold
  class_size = wandb.config.class_size

  train_loader, test_loader, model, tokenizer, classes = init_data_model(batch_size, class_size, test_size)
  model, tokenizer = train(train_loader, test_loader, model, tokenizer, lr, batch_size, threshold)

  # del test_labels
  del model
  del tokenizer
  torch.cuda.empty_cache()

  # return model, tokenizer

In [ ]:
wandb.agent(sweep_id, function=main, count=10)

wandb: Agent Starting Run: cpxhyxk1 with config:
wandb: 	batch_size: 8
wandb: 	class_size: 150
wandb: 	lr: 1.3298958782604504e-05
wandb: 	threshold: 1
wandb: Currently logged in as: ellieyhc (probgram). Use `wandb login --relogin` to force relogin

Dataset size: 450
        title  body
stance
center    150   150
left      150   150
right     150   150
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.007407407407407408
val_acc: 0.0
Epoch 1/20, Loss: 33.23231512308121
train_acc: 0.2740740740740741
val_acc: 0.13333333333333333
Epoch 2/20, Loss: 30.747042059898376
train_acc: 0.6790123456790124
val_acc: 0.5555555555555556
Epoch 3/20, Loss: 24.721015214920044
train_acc: 0.8716049382716049
val_acc: 0.4888888888888889
Epoch 4/20, Loss: 16.90356782078743
train_acc: 0.9407407407407408
val_acc: 0.6222222222222222
Epoch 5/20, Loss: 11.588650576770306
train_acc: 0.980246913580247
val_acc: 0.6666666666666666
Epoch 6/20, Loss: 6.459442168474197
train_acc: 0.9925925925925926
val_acc: 0.5777777777777777
Epoch 7/20, Loss: 4.004675943404436
train_acc: 0.9975308641975309
val_acc: 0.6222222222222222
Epoch 8/20, Loss: 2.2049700170755386
train_acc: 0.9851851851851852
val_acc: 0.7111111111111111
Epoch 9/20, Loss: 1.799944218248129
train_acc: 0.9975308641975309
val_acc: 0.6222222222222222
Epoch 10/20, Loss: 1.38328009378165
train_acc: 0.9975308641975309
val_acc: 0.5333333333333333
Epoch 11/20, Loss: 1.00208043679595
train_acc: 0.9975308641975309
val_acc: 0.6666666666666666
Epoch 12/20, Loss: 0.7930281478911638

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Agent Starting Run: qhahvhtz with config:
wandb: 	batch_size: 16
wandb: 	class_size: 150
wandb: 	lr: 2.5991714461288968e-05
wandb: 	threshold: 1.5

Dataset size: 450
        title  body
stance
center    150   150
left      150   150
right     150   150
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.12345679012345678
val_acc: 0.13333333333333333
Epoch 1/20, Loss: 16.431732177734375
train_acc: 0.7753086419753087
val_acc: 0.5777777777777777
Epoch 2/20, Loss: 14.194211184978485
train_acc: 0.9135802469135802
val_acc: 0.6888888888888889
Epoch 3/20, Loss: 9.301769897341728
train_acc: 0.9481481481481482
val_acc: 0.6444444444444445
Epoch 4/20, Loss: 5.305675752460957
train_acc: 0.9876543209876543
val_acc: 0.6666666666666666
Epoch 5/20, Loss: 3.1185249015688896
train_acc: 0.9950617283950617
val_acc: 0.7555555555555555
Epoch 6/20, Loss: 1.9646113254129887
train_acc: 0.9876543209876543
val_acc: 0.6888888888888889
Epoch 7/20, Loss: 1.0199636779725552

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Agent Starting Run: x99i0bv1 with config:
wandb: 	batch_size: 16
wandb: 	class_size: 250
wandb: 	lr: 3.322783254552369e-06
wandb: 	threshold: 1

Dataset size: 750
        title  body
stance
center    250   250
left      250   250
right     250   250
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.0
val_acc: 0.0
Epoch 1/20, Loss: 29.10788357257843
train_acc: 0.0
val_acc: 0.0
Epoch 2/20, Loss: 27.22971135377884
train_acc: 0.0
val_acc: 0.0
Epoch 3/20, Loss: 27.03159189224243
train_acc: 0.0014814814814814814
val_acc: 0.0
Epoch 4/20, Loss: 26.56839817762375
train_acc: 0.08888888888888889
val_acc: 0.05333333333333334
Epoch 5/20, Loss: 25.74675941467285
train_acc: 0.5214814814814814
val_acc: 0.30666666666666664
Epoch 6/20, Loss: 23.84251058101654
train_acc: 0.7155555555555555
val_acc: 0.6266666666666667
Epoch 7/20, Loss: 20.557847678661346
train_acc: 0.845925925925926
val_acc: 0.6
Epoch 8/20, Loss: 16.579698264598846
train_acc: 0.8814814814814815
val_acc: 0.6
Epoch 9/20, Loss: 14.051234260201454
train_acc: 0.9244444444444444
val_acc: 0.6
Epoch 10/20, Loss: 11.30922394990921
train_acc: 0.9422222222222222
val_acc: 0.6533333333333333
Epoch 11/20, Loss: 8.79142738878727
train_acc: 0.965925925925926
val_acc: 0.6933333333333334
Epoch 12/20, Loss: 7.020223535597324
train_acc: 0.9762962962962963
val_acc: 0.64
Epoch 13/20, Loss: 5.654948867857456
train_acc: 0.9762962962962963
val_acc: 0.7066666666666667
Epoch 14/20, Loss: 4.562003634870052
train_acc: 0.9792592592592593
val_acc: 0.68
Epoch 15/20, Loss: 4.231066696345806
train_acc: 0.9911111111111112
val_acc: 0.7066666666666667
Epoch 16/20, Loss: 3.6769326254725456
train_acc: 0.9911111111111112
val_acc: 0.68
Epoch 17/20, Loss: 2.8922908194363117
train_acc: 0.9866666666666667
val_acc: 0.72
Epoch 18/20, Loss: 2.600305173546076
train_acc: 0.9940740740740741
val_acc: 0.76
Epoch 19/20, Loss: 2.2941759265959263
train_acc: 0.9940740740740741
val_acc: 0.68
Epoch 20/20, Loss: 1.9814337715506554

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 0t9goa6f with config:
wandb: 	batch_size: 16
wandb: 	class_size: 200
wandb: 	lr: 5.756174854563884e-05
wandb: 	threshold: 3

Dataset size: 600
        title  body
stance
center    200   200
left      200   200
right     200   200
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.65
val_acc: 0.5
Epoch 1/20, Loss: 20.29754948616028
train_acc: 0.8888888888888888
val_acc: 0.6666666666666666
Epoch 2/20, Loss: 13.223955050110817
train_acc: 0.9092592592592592
val_acc: 0.6
Epoch 3/20, Loss: 8.400487966835499
train_acc: 0.9740740740740741
val_acc: 0.65
Epoch 4/20, Loss: 5.0969925336539745
train_acc: 0.9907407407407407
val_acc: 0.6333333333333333
Epoch 5/20, Loss: 3.232197416946292
train_acc: 0.9981481481481481
val_acc: 0.6166666666666667
Epoch 6/20, Loss: 1.427937338128686

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Agent Starting Run: awr9s3bc with config:
wandb: 	batch_size: 8
wandb: 	class_size: 150
wandb: 	lr: 9.623202006750852e-05
wandb: 	threshold: 0.5

Dataset size: 450
        title  body
stance
center    150   150
left      150   150
right     150   150
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.0
val_acc: 0.0
Epoch 1/20, Loss: 32.99369513988495
train_acc: 0.0024691358024691358
val_acc: 0.022222222222222223
Epoch 2/20, Loss: 32.68512016534805
train_acc: 0.009876543209876543
val_acc: 0.022222222222222223
Epoch 3/20, Loss: 32.39533752202988
train_acc: 0.0
val_acc: 0.0
Epoch 4/20, Loss: 32.73333114385605
train_acc: 0.09382716049382717
val_acc: 0.06666666666666667
Epoch 5/20, Loss: 32.75989234447479
train_acc: 0.014814814814814815
val_acc: 0.0
Epoch 6/20, Loss: 32.937021374702454
train_acc: 0.0
val_acc: 0.0
Epoch 7/20, Loss: 32.73188638687134
train_acc: 0.0
val_acc: 0.0
Epoch 8/20, Loss: 32.64429980516434
train_acc: 0.04938271604938271
val_acc: 0.06666666666666667
Epoch 9/20, Loss: 32.760459899902344
train_acc: 0.0049382716049382715
val_acc: 0.0
Epoch 10/20, Loss: 32.73306041955948
train_acc: 0.0049382716049382715
val_acc: 0.0
Epoch 11/20, Loss: 32.61657625436783
train_acc: 0.01728395061728395
val_acc: 0.0
Epoch 12/20, Loss: 32.991289496421814
train_acc: 0.0
val_acc: 0.0
Epoch 13/20, Loss: 32.772526025772095
train_acc: 0.0
val_acc: 0.0
Epoch 14/20, Loss: 32.660664200782776
train_acc: 0.0
val_acc: 0.0
Epoch 15/20, Loss: 32.67737036943436
train_acc: 0.04197530864197531
val_acc: 0.0
Epoch 16/20, Loss: 32.74177545309067
train_acc: 0.019753086419753086
val_acc: 0.022222222222222223
Epoch 17/20, Loss: 32.81681853532791
train_acc: 0.0
val_acc: 0.0
Epoch 18/20, Loss: 32.629419565200806
train_acc: 0.0
val_acc: 0.0
Epoch 19/20, Loss: 32.90508019924164
train_acc: 0.0
val_acc: 0.0
Epoch 20/20, Loss: 32.59370005130768

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Agent Starting Run: 6m3rwkoo with config:
wandb: 	batch_size: 8
wandb: 	class_size: 300
wandb: 	lr: 3.132066331971823e-05
wandb: 	threshold: 1.5

Dataset size: 900
        title  body
stance
center    300   300
left      300   300
right     300   300
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.7135802469135802
val_acc: 0.6444444444444445
Epoch 1/20, Loss: 60.00712788105011
train_acc: 0.8555555555555555
val_acc: 0.7666666666666667
Epoch 2/20, Loss: 39.30779805779457
train_acc: 0.9469135802469136
val_acc: 0.6222222222222222
Epoch 3/20, Loss: 19.410574104636908
train_acc: 0.9679012345679012
val_acc: 0.6777777777777778
Epoch 4/20, Loss: 9.91411099396646
train_acc: 0.9962962962962963
val_acc: 0.7333333333333333
Epoch 5/20, Loss: 6.883588599972427
train_acc: 0.9753086419753086
val_acc: 0.7666666666666667
Epoch 6/20, Loss: 3.5249824919737875
train_acc: 0.9987654320987654
val_acc: 0.6777777777777778
Epoch 7/20, Loss: 2.1745923487469554
train_acc: 1.0
val_acc: 0.7666666666666667
Epoch 8/20, Loss: 0.7647705804556608

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Agent Starting Run: iwtzbsvu with config:
wandb: 	batch_size: 8
wandb: 	class_size: 100
wandb: 	lr: 3.3145388492503516e-05
wandb: 	threshold: 1

Dataset size: 300
        title  body
stance
center    100   100
left      100   100
right     100   100
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.02962962962962963
val_acc: 0.0
Epoch 1/20, Loss: 21.96120697259903
train_acc: 0.26666666666666666
val_acc: 0.3333333333333333
Epoch 2/20, Loss: 21.07467257976532
train_acc: 0.8148148148148148
val_acc: 0.5333333333333333
Epoch 3/20, Loss: 16.466352880001068
train_acc: 0.9851851851851852
val_acc: 0.7333333333333333
Epoch 4/20, Loss: 9.065889716148376
train_acc: 0.825925925925926
val_acc: 0.7666666666666667
Epoch 5/20, Loss: 5.0009493716061115
train_acc: 0.9814814814814815
val_acc: 0.7333333333333333
Epoch 6/20, Loss: 2.906803684309125
train_acc: 0.9962962962962963
val_acc: 0.7333333333333333
Epoch 7/20, Loss: 1.8078293018043041
train_acc: 0.9925925925925926
val_acc: 0.6333333333333333
Epoch 8/20, Loss: 2.1134365405887365
train_acc: 1.0
val_acc: 0.7
Epoch 9/20, Loss: 0.8906216723844409

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Agent Starting Run: sbbjsdlg with config:
wandb: 	batch_size: 8
wandb: 	class_size: 200
wandb: 	lr: 1.464096716974041e-05
wandb: 	threshold: 2

Dataset size: 600
        title  body
stance
center    200   200
left      200   200
right     200   200
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.046296296296296294
val_acc: 0.016666666666666666
Epoch 1/20, Loss: 43.10095012187958
train_acc: 0.7148148148148148
val_acc: 0.5166666666666667
Epoch 2/20, Loss: 36.15548622608185
train_acc: 0.8703703703703703
val_acc: 0.6166666666666667
Epoch 3/20, Loss: 26.279584854841232
train_acc: 0.9648148148148148
val_acc: 0.6666666666666666
Epoch 4/20, Loss: 15.672308444976807
train_acc: 0.9796296296296296
val_acc: 0.6166666666666667
Epoch 5/20, Loss: 7.781303435564041
train_acc: 0.9962962962962963
val_acc: 0.6166666666666667
Epoch 6/20, Loss: 4.115889655426145
train_acc: 0.9925925925925926
val_acc: 0.6666666666666666
Epoch 7/20, Loss: 2.387312339618802
train_acc: 0.9944444444444445
val_acc: 0.6
Epoch 8/20, Loss: 1.629388471134007

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Agent Starting Run: y7mpyzdl with config:
wandb: 	batch_size: 8
wandb: 	class_size: 150
wandb: 	lr: 8.064182890369403e-06
wandb: 	threshold: 3

Dataset size: 450
        title  body
stance
center    150   150
left      150   150
right     150   150
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.0
val_acc: 0.0
Epoch 1/20, Loss: 32.99754345417023
train_acc: 0.022222222222222223
val_acc: 0.022222222222222223
Epoch 2/20, Loss: 31.43838620185852
train_acc: 0.6271604938271605
val_acc: 0.5111111111111111
Epoch 3/20, Loss: 28.493922293186188
train_acc: 0.9160493827160494
val_acc: 0.6444444444444445
Epoch 4/20, Loss: 21.528879553079605
train_acc: 0.8469135802469135
val_acc: 0.4444444444444444
Epoch 5/20, Loss: 14.497695237398148
train_acc: 0.9555555555555556
val_acc: 0.6222222222222222
Epoch 6/20, Loss: 9.451729856431484
train_acc: 0.980246913580247
val_acc: 0.7111111111111111
Epoch 7/20, Loss: 6.128531541675329
train_acc: 0.9950617283950617
val_acc: 0.6666666666666666
Epoch 8/20, Loss: 4.2771554030478
train_acc: 0.9950617283950617
val_acc: 0.6444444444444445
Epoch 9/20, Loss: 2.7371053993701935

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

wandb: Agent Starting Run: 5xhepkq6 with config:
wandb: 	batch_size: 8
wandb: 	class_size: 200
wandb: 	lr: 9.622225260813244e-06
wandb: 	threshold: 2.5

Dataset size: 600
        title  body
stance
center    200   200
left      200   200
right     200   200
Labels : [['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['center'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['left'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right'], ['right']]

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at launch/POLITICS and are newly initialized: ['classifier.out_proj.weight', 'classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

train_acc: 0.012962962962962963
val_acc: 0.0
Epoch 1/20, Loss: 43.52915334701538
train_acc: 0.6129629629629629
val_acc: 0.5
Epoch 2/20, Loss: 39.30546772480011
train_acc: 0.8888888888888888
val_acc: 0.65
Epoch 3/20, Loss: 28.884294345974922
train_acc: 0.9037037037037037
val_acc: 0.5666666666666667
Epoch 4/20, Loss: 17.755265399813652
train_acc: 0.9425925925925925
val_acc: 0.6333333333333333
Epoch 5/20, Loss: 11.538857772946358
train_acc: 0.9814814814814815
val_acc: 0.55
Epoch 6/20, Loss: 7.679401151835918
train_acc: 0.975925925925926
val_acc: 0.6166666666666667
Epoch 7/20, Loss: 5.539378985762596
train_acc: 0.9796296296296296
val_acc: 0.6
Epoch 8/20, Loss: 4.286137130111456
train_acc: 0.9962962962962963
val_acc: 0.6
Epoch 9/20, Loss: 3.1475172620266676
train_acc: 0.9962962962962963
val_acc: 0.5666666666666667
Epoch 10/20, Loss: 2.118522113189101

VBox(children=(Label(value='0.001 MB of 0.001 MB uploaded\r'), FloatProgress(value=1.0, max=1.0)))

In [ ]:
wandb.finish()

NameError: ignored

# Free up memory

In [ ]:
#Memory Management
# del df
# del test_labels
del model
del tokenizer
torch.cuda.empty_cache()